apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: strimzi-group
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: strimzi
spec:
  targetNamespaces:
  - ${OPERATOR_NAMESPACE}