apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-sub
  namespace: ${OPERATOR_NAMESPACE}
  labels:
    app: strimzi
spec:
  name: ${OLM_OPERATOR_NAME}
  source: ${OLM_SOURCE_NAME}
  sourceNamespace: ${OLM_SOURCE_NAMESPACE}
  startingCSV: ${OLM_APP_BUNDLE_PREFIX}.v${OLM_OPERATOR_VERSION}
  channel: ${OLM_CHANNEL}
  installPlanApproval: ${OLM_INSTALL_PLAN_APPROVAL}
  config:
    env:
      - name: STRIMZI_LOG_LEVEL
        value: "DEBUG"
      - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
        value: "${STRIMZI_FULL_RECONCILIATION_INTERVAL_MS}"
      - name: STRIMZI_OPERATION_TIMEOUT_MS
        value: "${STRIMZI_OPERATION_TIMEOUT_MS}"
      - name: STRIMZI_FEATURE_GATES
        value: "${STRIMZI_FEATURE_GATES}"
